import { headers } from "next/headers";
import { INDEXER_URL } from "@/app/_lib/urls";

// Regenerate per request so the document always reflects the live origin and
// configured endpoints. It's a static string build — no network calls — so the
// cost is negligible.
export const dynamic = "force-dynamic";
export const revalidate = 0;

function authBaseUrl(): string {
  return (
    process.env.NEXT_PUBLIC_AUTH_BASE_URL?.trim().replace(/\/$/, "") ||
    "https://auth.gainforest.app"
  );
}

async function resolveOrigin(): Promise<string> {
  const headerList = await headers();
  const host = headerList.get("host") ?? "certs.gainforest.app";
  const proto = headerList.get("x-forwarded-proto") ?? "https";
  return `${proto}://${host}`;
}

export async function GET() {
  const origin = await resolveOrigin();
  const auth = authBaseUrl();
  const body = buildSkillMd(origin, auth, INDEXER_URL);
  return new Response(body, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "no-store, must-revalidate",
    },
  });
}

function buildSkillMd(origin: string, auth: string, indexer: string): string {
  const generatedAt = new Date().toISOString();
  return `# GainForest agent skill (read + write)

> Generated by ${origin}/skill.md. Canonical, agent-readable guide for reading
> GainForest data and writing records on a user's behalf with an agent API key.
> Reading is keyless; writing needs a Personal Access Token the user mints in
> their settings.

## What GainForest is

GainForest (the certs/bumicerts app) is an ATProto-native platform for
nature stewardship data: trees and tree groups, field observations, photos and
audio, sites, certificates ("bumicerts"), badges, and funding. Every durable
record lives on a user's ATProto PDS (personal account) or a shared
organization account (a Certified Group Service "group"). The central auth
service at \`${auth}\` holds each user's restorable OAuth session and performs
the actual writes.

## Setup — connecting your API key (one-time)

1. **Generate.** Your human opens their **Settings → AI agent keys** and
   creates a key. It looks like \`gf_pat_…\` and is shown **once**.
2. **Store** it as an env var, e.g. \`GAINFOREST_API_KEY\`. Never hard-code the
   raw token into prompts, code, or records.
3. **Verify** the key and learn your DID:

\`\`\`bash
curl -s ${auth}/api/auth/session -H "Authorization: Bearer $GAINFOREST_API_KEY"
# → { "isLoggedIn": true, "did": "did:plc:…", "viaApiKey": true }
# → { "isLoggedIn": false }  means the key is bad or revoked — ask for a new one
\`\`\`

The write recipes below use \`$TOKEN\` as shorthand — set
\`TOKEN="$GAINFOREST_API_KEY"\`. Records land on the **user's own PDS**: you act
on their behalf, never holding their PDS credentials.

## Reading — the indexer (keyless)

All reads go through the GainForest Hyperindex GraphQL endpoint, which serves
\`access-control-allow-origin: *\`:

- **Indexer:** \`${indexer}\`

Query the typed collections directly, e.g. trees a DID owns:

\`\`\`bash
curl -s -X POST ${indexer} \\
  -H 'Content-Type: application/json' \\
  -d '{ "query": "query($did: String!, $first: Int) { appGainforestDwcOccurrence(where: { did: { eq: $did } }, first: $first, sortDirection: DESC, sortBy: createdAt) { edges { node { uri rkey value } } } }", "variables": { "did": "<did>", "first": 50 } }'
\`\`\`

Reads never hit the auth service — the data lives on real PDSes that the
indexer mirrors. Resolve handles → DIDs with the public resolver
(\`https://public.api.bsky.app/xrpc/com.atproto.identity.resolveHandle?handle=<handle>\`)
and treat DIDs as opaque (\`did:plc:\` and \`did:web:\` both occur).

## Collections an agent can write

Keys may write the \`app.gainforest.*\`, \`app.certified.*\`, and
\`org.hypercerts.*\` namespaces only. The common ones:

\`\`\`
app.gainforest.dwc.occurrence   — a tree / occurrence (Darwin Core)
app.gainforest.dwc.measurement  — a measurement linked to an occurrence
app.gainforest.dwc.dataset      — a tree group / dataset
app.gainforest.dwc.event        — a sampling event
app.gainforest.ac.multimedia    — a photo (Audubon Core), links an occurrence
app.gainforest.ac.audio         — an audio recording
app.gainforest.ac.deployment    — a recorder deployment
app.certified.location          — a site / certified location
app.certified.badge.definition  — a badge definition
app.certified.badge.award       — a badge award
org.hypercerts.claim.activity   — a funding claim / activity
\`\`\`

The agent can never change account settings, the user's Bluesky profile, or
manage other keys.

## Writing — personal repo

Write to the signed-in user's own repo via the auth service. Body shape:
\`{ operation, collection, rkey?, record }\`. \`createdAt\` (ISO 8601) belongs in
\`record\`; \`$type\` is filled in for you.

\`\`\`bash
# Create — returns { uri, cid }
curl -s -X POST ${auth}/api/atproto/mutation \\
  -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\
  -d '{ "operation": "createRecord", "collection": "app.gainforest.dwc.occurrence",
        "record": { "scientificName": "Quercus robur", "eventDate": "2026-01-01",
                    "decimalLatitude": "1.23", "decimalLongitude": "4.56",
                    "basisOfRecord": "HumanObservation", "createdAt": "2026-01-01T00:00:00Z" } }'

# Update (full replace) — body: { operation: "putRecord", collection, rkey, record }
# Delete                — body: { operation: "deleteRecord", collection, rkey }
# Upload a blob         — body: { operation: "uploadBlob", blobData: "<base64>", blobMimeType: "image/jpeg" }
\`\`\`

## Writing — organization (group) repo

To write to a shared organization account, hit the CGS endpoint and name the
group with \`repo\` (its handle or DID) in the body. Only record writes and
blob uploads are allowed with a key — group lifecycle, membership, roles, and
key management require a signed-in owner/admin in the browser.

\`\`\`bash
curl -s -X POST ${auth}/api/cgs/mutation \\
  -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\
  -d '{ "operation": "createRecord", "repo": "<org-handle-or-did>",
        "collection": "app.gainforest.dwc.occurrence",
        "record": { "scientificName": "Quercus robur", "eventDate": "2026-01-01",
                    "decimalLatitude": "1.23", "decimalLongitude": "4.56",
                    "basisOfRecord": "HumanObservation", "createdAt": "2026-01-01T00:00:00Z" } }'
\`\`\`

The user must be a member of the group with a role that permits the write; the
key acts on their behalf within that role.

## Notes

- Always include \`createdAt\` (ISO 8601) in records.
- Keep StrongRefs from create responses (\`{ uri, cid }\`) to link records
  (e.g. a measurement's \`occurrenceRef\`, a photo's \`occurrenceRef\`).
- A bad/revoked key returns \`{ "isLoggedIn": false }\` from the verify call and
  a 401 from the mutation endpoints — stop and ask your human for a fresh key.
- Full auth-service contract: \`curl -s ${auth}/skill\`.

---

Generated at ${generatedAt}
`;
}
