import { headers } from "next/headers";
import { INDEXER_URL } from "@/app/_lib/urls";

// Regenerate per request so the document always reflects the live origin and
// configured endpoints. It's a static string build — no network calls — so the
// cost is negligible.
export const dynamic = "force-dynamic";
export const revalidate = 0;

function authBaseUrl(): string {
  return (
    process.env.NEXT_PUBLIC_AUTH_BASE_URL?.trim().replace(/\/$/, "") ||
    "https://auth.gainforest.app"
  );
}

async function resolveOrigin(): Promise<string> {
  const headerList = await headers();
  const host = headerList.get("host") ?? "certs.gainforest.app";
  const proto = headerList.get("x-forwarded-proto") ?? "https";
  return `${proto}://${host}`;
}

export async function GET() {
  const origin = await resolveOrigin();
  const auth = authBaseUrl();
  const body = buildSkillMd(origin, auth, INDEXER_URL);
  return new Response(body, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "no-store, must-revalidate",
    },
  });
}

function buildSkillMd(origin: string, auth: string, indexer: string): string {
  const generatedAt = new Date().toISOString();
  return `# GainForest agent skill — upload observations, create projects, build evidence timelines

> Generated by ${origin}/skill.md. Canonical, agent-readable guide for an AI
> agent helping a nature steward record their work on GainForest: logging field
> **observations**, creating **projects** with their certificate ("cert"), and
> attaching **evidence** to a project's timeline. Reading is keyless; writing
> needs a Personal Access Token the user mints in their settings.

## What you're helping with

GainForest (the certs/bumicerts app) is an ATProto-native platform for nature
stewardship. The three jobs this skill optimizes for:

1. **Observations** — geotagged species sightings (trees, plants, wildlife),
   optionally with a photo and a measurement. Stored as
   \`app.gainforest.dwc.occurrence\` (Darwin Core) records on the user's repo.
2. **Projects & certs** — a **project** (\`org.hypercerts.collection\`) is the
   public story of a piece of regenerative work; it carries exactly one
   **cert** (\`org.hypercerts.claim.activity\`) holding the structured claim
   (scope, dates, contributors, sites). They're created together, 1:1.
3. **Evidence timelines** — dated evidence entries
   (\`org.hypercerts.context.attachment\`) attached to a cert, each linking
   files, external URLs, or other records (observations, datasets, photos).

Every record lives on the user's own ATProto PDS (personal account) or a shared
organization account. You write **through** the central auth service — you never
hold the user's PDS credentials.

## Setup — connecting your API key (one-time)

1. **Generate.** The user opens **Settings → AI agent keys** and creates a key
   (looks like \`gf_pat_…\`, shown once).
2. **Store** it as an env var, e.g. \`GAINFOREST_API_KEY\`. Never hard-code it.
3. **Verify** it and learn the user's account id (DID):

\`\`\`bash
curl -s ${auth}/api/auth/session -H "Authorization: Bearer $GAINFOREST_API_KEY"
# → { "isLoggedIn": true, "did": "did:plc:…", "viaApiKey": true }
# → { "isLoggedIn": false }  ⇒ key is bad/revoked; ask the user for a new one
\`\`\`

Recipes below use \`$TOKEN\` (\`TOKEN="$GAINFOREST_API_KEY"\`) and \`$AUTH\`
(\`AUTH="${auth}"\`).

## How writes work

All writes are \`POST $AUTH/api/atproto/mutation\` with a JSON body
\`{ operation, collection, rkey?, record }\`:

\`\`\`bash
# create → returns { uri, cid } (KEEP BOTH: they're the StrongRef for links)
curl -s -X POST $AUTH/api/atproto/mutation \\
  -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\
  -d '{ "operation":"createRecord", "collection":"<nsid>", "record": { … } }'

# update (full replace): { "operation":"putRecord", "collection", "rkey", "record" }
# delete:                { "operation":"deleteRecord", "collection", "rkey" }
# upload a file/photo:   { "operation":"uploadBlob", "blobData":"<base64>", "blobMimeType":"image/jpeg" }
\`\`\`

Rules that matter:

- **Always set \`createdAt\`** (ISO 8601) inside \`record\`. \`$type\` is filled
  in for you from \`collection\`, but including it never hurts.
- **\`uploadBlob\` returns a blob object** \`{ "$type":"blob", "ref":…, "mimeType":…, "size":… }\`.
  Capture it and embed it where a record expects a blob (photos, banners, files).
- **Coordinates are strings**, not numbers, on occurrence records
  (\`"decimalLatitude":"1.2345"\`).
- **\`eventDate\` must not be in the future.**
- Keys may only write \`app.gainforest.*\`, \`app.certified.*\`, and
  \`org.hypercerts.*\`; never account settings, the Bluesky profile, or other keys.

### Writing to an organization instead of the personal account

To write into a shared organization (a Certified Group), use
\`POST $AUTH/api/cgs/mutation\` and add \`"repo":"<org-handle-or-did>"\` to the
body. Same operations and record shapes; the user must be a member of that org.

## Reading (keyless) — find context before you write

Reads go through the indexer GraphQL endpoint (CORS-open):

- **Indexer:** \`${indexer}\`

Resolve a handle to a DID:
\`https://public.api.bsky.app/xrpc/com.atproto.identity.resolveHandle?handle=<handle>\`.
List a user's existing sites/projects before creating duplicates, e.g. sites:

\`\`\`bash
curl -s -X POST ${indexer} -H 'Content-Type: application/json' -d '{
  "query":"query($did:String!,$first:Int){ appCertifiedLocation(where:{did:{eq:$did}},first:$first){ edges{ node{ uri rkey value } } } }",
  "variables":{"did":"<did>","first":50}
}'
\`\`\`

---

# Workflow 1 — Upload an observation

An observation is one \`app.gainforest.dwc.occurrence\` record. A photo and a
measurement are optional add-ons that reference it.

### 1a. Create the occurrence

\`\`\`bash
curl -s -X POST $AUTH/api/atproto/mutation \\
  -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\
  -d '{ "operation":"createRecord", "collection":"app.gainforest.dwc.occurrence",
    "record": {
      "scientificName": "Quercus robur",
      "vernacularName": "English oak",
      "eventDate": "2026-01-15",
      "decimalLatitude": "1.2345",
      "decimalLongitude": "103.6789",
      "basisOfRecord": "HumanObservation",
      "occurrenceStatus": "present",
      "geodeticDatum": "EPSG:4326",
      "license": "CC-BY-4.0",
      "kingdom": "Plantae",
      "locality": "Riverbank plot",
      "occurrenceRemarks": "Planted seedling, healthy.",
      "recordedBy": "Field team",
      "createdAt": "2026-01-15T09:00:00Z"
    } }'
# → { "uri": "at://…/app.gainforest.dwc.occurrence/<rkey>", "cid": "…" }
\`\`\`

Field notes:

- **Required-ish:** \`scientificName\`, \`eventDate\`, \`decimalLatitude\`,
  \`decimalLongitude\`, \`createdAt\`. If species is unknown, use a
  higher-rank name (e.g. \`"Plantae"\`) and set \`vernacularName\`.
- Sensible defaults if omitted: \`basisOfRecord\` "HumanObservation"
  (use "MachineObservation" for sensor/drone data), \`occurrenceStatus\`
  "present", \`geodeticDatum\` "EPSG:4326", \`license\` "CC-BY-4.0",
  \`kingdom\` "Plantae". \`occurrenceID\` is auto-generated if omitted.
- **Link it (optional):** \`"siteRef":"at://…/app.certified.location/<rkey>"\`
  to attach to a site (see Workflow 2), and/or
  \`"projectRef":"at://…/org.hypercerts.collection/<rkey>"\` to attach to a project.
- Other optional fields: \`country\`, \`countryCode\`, \`habitat\`,
  \`samplingProtocol\`, \`establishmentMeans\`.

### 1b. Attach a photo (so it shows in the explorer)

Two steps: upload the bytes, then **copy the blob onto the occurrence's
\`imageEvidence\`** — the explorer reads an occurrence's photo from there.

\`\`\`bash
# 1. upload → returns the blob object
BLOB=$(curl -s -X POST $AUTH/api/atproto/mutation \\
  -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\
  -d "{ \\"operation\\":\\"uploadBlob\\", \\"blobData\\":\\"$(base64 -w0 photo.jpg)\\", \\"blobMimeType\\":\\"image/jpeg\\" }")
# BLOB = { "$type":"blob", "ref":{…}, "mimeType":"image/jpeg", "size":12345 }

# 2. putRecord the occurrence with imageEvidence set to that blob.
#    Re-send the full record (fetch it first if you don't have it) plus:
#    "imageEvidence": { "$type": "app.gainforest.common.defs#image", "file": <BLOB> }
\`\`\`

Optional: you can *also* create a standalone gallery photo record
(\`app.gainforest.ac.multimedia\`) that points back at the occurrence:

\`\`\`json
{ "operation":"createRecord", "collection":"app.gainforest.ac.multimedia",
  "record": { "file": <BLOB>, "format":"image/jpeg",
    "occurrenceRef":"at://…/app.gainforest.dwc.occurrence/<rkey>",
    "subjectPart":"whole", "caption":"Seedling at planting",
    "createdAt":"2026-01-15T09:05:00Z" } }
\`\`\`

### 1c. Add a tree measurement (optional)

\`\`\`json
{ "operation":"createRecord", "collection":"app.gainforest.dwc.measurement",
  "record": {
    "occurrenceRef":"at://…/app.gainforest.dwc.occurrence/<rkey>",
    "result": { "$type":"app.gainforest.dwc.measurement#floraMeasurement",
      "dbh": 12.4, "totalHeight": 3.2, "basalDiameter": 8.1, "canopyCoverPercent": 55 },
    "createdAt":"2026-01-15T09:10:00Z" } }
\`\`\`

(\`dbh\` = diameter at breast height, cm; \`totalHeight\` m; all fields optional —
send what was measured.)

---

# Workflow 2 — Create a project (with its cert)

A project and its cert are created **together**: create the cert first, then the
project that links it via \`items[]\`. Create a **site** first if the work has a
location.

### 2a. (Optional) Create a site

\`\`\`json
{ "operation":"createRecord", "collection":"app.certified.location",
  "record": {
    "$type":"app.certified.location", "lpVersion":"1.0",
    "srs":"http://www.opengis.net/def/crs/OGC/1.3/CRS84",
    "locationType":"coordinate-decimal",
    "location": { "$type":"app.certified.location#string", "string":"1.2345,103.6789" },
    "name":"Riverbank restoration plot",
    "createdAt":"2026-01-15T09:00:00Z" } }
# → keep { uri, cid } to reference as a site
\`\`\`

### 2b. Create the cert (the structured claim)

\`\`\`json
{ "operation":"createRecord", "collection":"org.hypercerts.claim.activity",
  "record": {
    "title":"Riverbank reforestation 2026",
    "shortDescription":"Restoring 2 ha of degraded riverbank with native trees.",
    "description": { "$type":"org.hypercerts.defs#descriptionString",
      "value":"Full story of the work, methods, and community involvement." },
    "workScope": { "$type":"org.hypercerts.claim.activity#workScopeString",
      "scope":"reforestation, agroforestry" },
    "startDate":"2026-01-01T00:00:00Z",
    "endDate":"2026-06-30T00:00:00Z",
    "contributors": [ { "contributorIdentity": {
      "$type":"org.hypercerts.claim.activity#contributorIdentity",
      "identity":"did:plc:… or a plain name" } } ],
    "locations": [ { "uri":"<site uri>", "cid":"<site cid>" } ],
    "createdAt":"2026-01-15T10:00:00Z" } }
# → keep { uri, cid } — the project links to this cert
\`\`\`

Notes: omit \`endDate\` for ongoing work. \`workScope.scope\` is a
comma-separated tag list. \`locations[]\` are StrongRefs to sites from 2a. To set
a cover image, \`uploadBlob\` then add
\`"image": { "$type":"org.hypercerts.defs#smallImage", "image": <BLOB> }\`.

### 2c. Create the project that carries the cert

\`\`\`json
{ "operation":"createRecord", "collection":"org.hypercerts.collection",
  "record": {
    "title":"Riverbank reforestation 2026",
    "type":"project",
    "shortDescription":"Restoring 2 ha of degraded riverbank with native trees.",
    "description": { "$type":"org.hypercerts.defs#descriptionString",
      "value":"Public project overview." },
    "items": [ { "itemIdentifier": { "uri":"<cert uri>", "cid":"<cert cid>" } } ],
    "createdAt":"2026-01-15T10:05:00Z" } }
\`\`\`

\`type\` is always \`"project"\`. \`items[]\` must include the cert's StrongRef
from 2b (this is what makes the project show its cert). For a banner image,
\`uploadBlob\` then add
\`"banner": { "$type":"org.hypercerts.defs#largeImage", "image": <BLOB> }\`.

The project is then viewable at \`${origin}/cert/<did>/<cert-rkey>\` and listed
on the user's profile.

---

# Workflow 3 — Build an evidence timeline

A cert's timeline is the set of \`org.hypercerts.context.attachment\` records
whose **first subject is that cert**, shown newest-first by \`createdAt\`. Each
attachment is one dated evidence entry that can carry files, external links, and
references to observations/datasets.

\`\`\`json
{ "operation":"createRecord", "collection":"org.hypercerts.context.attachment",
  "record": {
    "title":"Drone survey — January 2026",
    "contentType":"report",
    "subjects": [
      { "$type":"com.atproto.repo.strongRef", "uri":"<cert uri>",  "cid":"<cert cid>"  },
      { "$type":"com.atproto.repo.strongRef", "uri":"<site uri>",  "cid":"<site cid>"  }
    ],
    "content": [
      { "$type":"org.hypercerts.defs#uri", "uri":"https://example.org/survey.pdf" },
      { "$type":"org.hypercerts.defs#uri", "uri":"at://…/app.gainforest.dwc.occurrence/<rkey>" },
      { "$type":"org.hypercerts.defs#smallBlob", "blob": <BLOB> }
    ],
    "description": { "$type":"org.hypercerts.defs#descriptionString",
      "value":"What this evidence shows and how it was collected." },
    "createdAt":"2026-01-20T12:00:00Z" } }
\`\`\`

Rules:

- **\`subjects[0]\` MUST be the cert** (\`org.hypercerts.claim.activity\`) the
  evidence belongs to — that's the link that places it on the timeline. Add more
  subjects (a site, a tree dataset) for context. Each subject is a full
  \`com.atproto.repo.strongRef\` with both \`uri\` and \`cid\`.
- **\`content[]\`** mixes three item types: \`#uri\` for an external link **or**
  an \`at://\` reference to another record (observation, dataset, photo);
  \`#smallBlob\` for a file you \`uploadBlob\`-ed first (image/PDF/etc.).
- \`contentType\` is a short free-text category (e.g. \`"photo"\`, \`"report"\`,
  \`"field-note"\`). \`title\` is required; \`description\` is optional notes.
- To build a timeline from existing observations, list the user's occurrences
  from the indexer, then create one attachment per milestone with those
  occurrence \`at://\` URIs in \`content[]\`.

---

## Collections quick reference

\`\`\`
app.gainforest.dwc.occurrence   — observation / species sighting (Darwin Core)
app.gainforest.dwc.measurement  — measurement linked to an occurrence (occurrenceRef)
app.gainforest.dwc.dataset      — a tree group / dataset of occurrences
app.gainforest.ac.multimedia    — a photo (links an occurrence via occurrenceRef)
app.certified.location          — a site / place (referenced by siteRef / locations)
org.hypercerts.claim.activity   — the cert: the structured claim of work
org.hypercerts.collection       — the project (type "project"; carries the cert in items[])
org.hypercerts.context.attachment — a timeline evidence entry (subjects[0] = the cert)
\`\`\`

## Verify & clean up

- Verify a key: \`GET $AUTH/api/auth/session\` with the bearer.
- Wrote something by mistake? \`deleteRecord\` with the \`{ collection, rkey }\`
  from the create response's \`uri\`.
- Full auth-service contract: \`curl -s $AUTH/skill\`.

Always echo back the created record URLs (\`${origin}/cert/<did>/<rkey>\` for
projects, the user's profile for observations) so the steward can review.

---

Generated at ${generatedAt}
`;
}
