import "server-only";
import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { headers } from "next/headers";
import { getAuthBaseUrl, getAuthForwardCookie } from "./auth";
import {
  DATA_JOBS_AGENT_KEY_NAME,
  isDataJobsAgentKeyName,
  type DataJob,
  type DataJobStatus,
} from "./data-jobs-shared";
import {
  getS3Config,
  getJson,
  putJson,
  deleteObject,
  listKeys,
  type S3Config,
} from "./s3-storage";

/**
 * Data batch jobs — server-side model.
 *
 * A "job" is one huge archive (photos + KoboToolbox CSVs) submitted by a
 * field partner for the GainForest team to review and publish on their
 * behalf. Everything lives in one S3-compatible bucket (Cloudflare R2):
 *
 *   jobs/{jobId}/archive.zip     the uploaded archive (multipart, browser→bucket)
 *   meta/{jobId}.json            the job record (this module's source of truth)
 *   by-user/{did}/{jobId}        pointer so "my jobs" doesn't scan everything
 *   agent-keys/{did}.json        encrypted publish-on-behalf agent key
 *
 * Publishing uses a regular GainForest agent key (`gf_pat_…`) minted from the
 * submitter's sign-in with the canonical name in `DATA_JOBS_AGENT_KEY_NAME` —
 * visible and revocable in Settings → AI agent keys, exactly like Tainá's.
 * The key is encrypted at rest with `DATA_JOBS_KEY_SECRET`; the Next.js app
 * never stores it in plaintext. Who owns a job always comes from the session,
 * never the request body.
 */

export type StoredDataJob = Omit<DataJob, "hasAgentKey"> & {
  /** Multipart upload id while the browser is still streaming parts. */
  uploadId: string | null;
  /** Object key of the archive inside the bucket. */
  storageKey: string;
};

export function isDataJobsConfigured(): boolean {
  return getS3Config() !== null;
}

export function requireS3(): S3Config {
  const config = getS3Config();
  if (!config) throw new Error("data jobs storage is not configured (DATA_JOBS_S3_* env)");
  return config;
}

const metaKey = (jobId: string) => `meta/${jobId}.json`;
const userPointerKey = (did: string, jobId: string) => `by-user/${did}/${jobId}`;
const agentKeyKey = (did: string) => `agent-keys/${did}.json`;
export const archiveKey = (jobId: string) => `jobs/${jobId}/archive.zip`;

export function newJobId(): string {
  return `${Date.now().toString(36)}-${randomBytes(5).toString("hex")}`;
}

/** Job ids are generated by `newJobId` — reject anything else before it hits storage keys. */
export function isValidJobId(jobId: string): boolean {
  return /^[a-z0-9]{6,12}-[a-f0-9]{10}$/.test(jobId);
}

/* ─────────────────────────────── Job CRUD ─────────────────────────────── */

export async function saveDataJob(job: StoredDataJob): Promise<void> {
  const config = requireS3();
  await putJson(config, metaKey(job.id), job);
  await putJson(config, userPointerKey(job.did, job.id), { id: job.id });
}

export async function getDataJob(jobId: string): Promise<StoredDataJob | null> {
  if (!isValidJobId(jobId)) return null;
  return getJson<StoredDataJob>(requireS3(), metaKey(jobId));
}

export async function updateDataJob(
  jobId: string,
  patch: Partial<Pick<StoredDataJob, "status" | "sizeBytes" | "uploadId" | "publishedCount" | "reviewNote">>,
): Promise<StoredDataJob | null> {
  const job = await getDataJob(jobId);
  if (!job) return null;
  const next: StoredDataJob = { ...job, ...patch, updatedAt: new Date().toISOString() };
  await saveDataJob(next);
  return next;
}

export async function deleteDataJob(job: StoredDataJob): Promise<void> {
  const config = requireS3();
  await deleteObject(config, metaKey(job.id));
  await deleteObject(config, userPointerKey(job.did, job.id));
  await deleteObject(config, job.storageKey).catch(() => {});
}

export async function listJobsForUser(did: string): Promise<StoredDataJob[]> {
  const config = requireS3();
  const pointers = await listKeys(config, `by-user/${did}/`);
  const ids = pointers.map((key) => key.split("/").pop()!).filter(isValidJobId);
  const jobs = await Promise.all(ids.map((id) => getJson<StoredDataJob>(config, metaKey(id)).catch(() => null)));
  return jobs.filter((job): job is StoredDataJob => job !== null).sort(byNewest);
}

export async function listAllJobs(): Promise<StoredDataJob[]> {
  const config = requireS3();
  const keys = await listKeys(config, "meta/");
  const jobs = await Promise.all(keys.map((key) => getJson<StoredDataJob>(config, key).catch(() => null)));
  return jobs.filter((job): job is StoredDataJob => job !== null).sort(byNewest);
}

function byNewest(a: StoredDataJob, b: StoredDataJob): number {
  return b.createdAt.localeCompare(a.createdAt);
}

/** Strip internal fields before a job record leaves the server. */
export function toPublicJob(job: StoredDataJob, hasAgentKey: boolean): DataJob {
  const { uploadId: _uploadId, storageKey: _storageKey, ...pub } = job;
  return { ...pub, hasAgentKey };
}

/* ──────────────── Publish-on-behalf agent key (gf_pat_…) ──────────────── */

type AgentTokenMeta = { id: string; name: string };

async function authTokensRequest(
  method: "GET" | "POST" | "DELETE",
  body?: Record<string, unknown>,
): Promise<Response> {
  const headerList = await headers();
  const cookie = getAuthForwardCookie(headerList.get("cookie"));
  return fetch(new URL("/api/account/tokens", getAuthBaseUrl()), {
    method,
    headers: {
      ...(cookie ? { cookie } : {}),
      ...(body ? { "content-type": "application/json" } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
    cache: "no-store",
    signal: AbortSignal.timeout(15_000),
  });
}

/**
 * Mint a fresh publish-on-behalf agent key for the signed-in user (retiring
 * any older ones with the canonical name) and store it encrypted in the
 * bucket. Called once, when the user first consents on the submit form.
 * Revoking the key in Settings → AI agent keys disables publishing instantly;
 * the stale ciphertext left behind is useless.
 */
export async function mintAndStoreAgentKey(did: string): Promise<void> {
  // Retire older data-jobs keys so Settings never shows confusing duplicates.
  const listResponse = await authTokensRequest("GET");
  if (listResponse.ok) {
    const data = (await listResponse.json().catch(() => ({}))) as { tokens?: AgentTokenMeta[] };
    const staleIds = (data.tokens ?? []).filter((t) => isDataJobsAgentKeyName(t.name)).map((t) => t.id);
    for (const id of staleIds) {
      await authTokensRequest("DELETE", { id }).catch(() => {});
    }
  }

  const response = await authTokensRequest("POST", { name: DATA_JOBS_AGENT_KEY_NAME });
  const data = (await response.json().catch(() => ({}))) as { token?: string; error?: string };
  if (!response.ok || !data.token) {
    throw new Error(data.error ?? `agent key mint failed (${response.status})`);
  }

  await putJson(requireS3(), agentKeyKey(did), {
    name: DATA_JOBS_AGENT_KEY_NAME,
    mintedAt: new Date().toISOString(),
    ...encryptSecret(data.token),
  });
}

export async function hasStoredAgentKey(did: string): Promise<boolean> {
  const record = await getJson<{ ciphertext?: string }>(requireS3(), agentKeyKey(did)).catch(() => null);
  return Boolean(record?.ciphertext);
}

/** Decrypt the stored key for the review team's publish flow (admin-gated callers only). */
export async function readStoredAgentKey(did: string): Promise<string | null> {
  const record = await getJson<{ ciphertext: string; iv: string; tag: string }>(
    requireS3(),
    agentKeyKey(did),
  ).catch(() => null);
  if (!record?.ciphertext) return null;
  try {
    return decryptSecret(record);
  } catch {
    return null;
  }
}

export async function deleteStoredAgentKey(did: string): Promise<void> {
  await deleteObject(requireS3(), agentKeyKey(did));
}

/* ─────────────────────── At-rest encryption (AES-GCM) ─────────────────────── */

function encryptionKey(): Buffer {
  const secret = process.env.DATA_JOBS_KEY_SECRET?.trim();
  if (!secret) {
    if (process.env.NODE_ENV === "production") {
      throw new Error("DATA_JOBS_KEY_SECRET is required to store agent keys");
    }
    return createHash("sha256").update("dev-data-jobs-secret").digest();
  }
  return createHash("sha256").update(secret).digest();
}

function encryptSecret(plaintext: string): { ciphertext: string; iv: string; tag: string } {
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  return {
    ciphertext: ciphertext.toString("base64"),
    iv: iv.toString("base64"),
    tag: cipher.getAuthTag().toString("base64"),
  };
}

function decryptSecret(record: { ciphertext: string; iv: string; tag: string }): string {
  const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(record.iv, "base64"));
  decipher.setAuthTag(Buffer.from(record.tag, "base64"));
  return Buffer.concat([decipher.update(Buffer.from(record.ciphertext, "base64")), decipher.final()]).toString("utf8");
}

/* ─────────────────────────── Status transitions ─────────────────────────── */

export function isAdminSettableStatus(status: string): status is DataJobStatus {
  return status === "received" || status === "inReview" || status === "published" || status === "needsAttention";
}
